### ISSUE TITLE
Cron job for syncing user to maestro services

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/dev-scripts#13]
https://github.com/IN-CORE/dev-scripts/blob/master/incore-services/sync_users_roles_steps_playbook.py#L187

This is the script

- I would need bearer token
- Only the last step create user need to be run repetitively. The other thing just need to run once

**Comment by robkooper** [comment]
so this talks to keycloak to get information and store in maestro database. I think we can do the same as we do for cronjob for spaces and users: https://github.com/IN-CORE/incore-helm/blob/main/templates/svc-space/cronjob.yaml (we can probably leverage of this code to do that when moving from ldap to keycloak.

Should this code be in platform or dev-scripts, it seems there is overlap in those repos.

**Comment by robkooper** [comment]
also do we build docker images already?
