### ISSUE TITLE
SLC retrofit cost script

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/dev-scripts#37]
This script will be a step used in Datawolf.
For SLC, retrofit cost is given as a table with "guid" "cost" as it is without any calculation.
Related to task https://github.com/IN-CORE/pyincore/issues/490

---

Todos:
1. Clean up the table to only keep GUID and retrofit cost
[Salt_Lake_City_Build_W_Cost.csv](https://github.com/IN-CORE/dev-scripts/files/14299775/Salt_Lake_City_Build_W_Cost.csv)

2. Write a function
- Input: 
  - Retrofit Strategy csv. See an example here: [SLC_retrofit_plan.csv](https://github.com/IN-CORE/dev-scripts/files/14299940/SLC_retrofit_plan.csv)
  - Retrofit Cost Table (in step 1)
- Output:  
  - guid, cost, and total cost
  - JSON might be easier for frontend to consume
- Maybe just use pandas join

**Comment by ywkim312** [comment]
Is there any existing script that I can reference to see see what kind of steps I have to do when I write a step 2 writing funciton?

**Comment by longshuicy** [comment]
@navarroc could you point @ywkim312 to the repo that you keep the datawolf steps scripts? thanks~~~

**Comment by navarroc** [comment]
Yes, here's a good example: https://github.com/navarroc/pyincore-datawolf/blob/main/building_dmg_summary.py

You can really look at any of them in the pyincore-datawolf repository, but they are all of similar shape. Let me know if you have questions @ywkim312

**Comment by ywkim312** [comment]
SLC
There are only URML and UR*, only two types of retrofit cost
They already pre calucluated for each building
Clean up the table, guid, and cost (probably only keep the buildings that has cost)
Use this as static input as CSV
Create a script 
User give give their own Retrofit Strategy csv as an input
total number of building 
total cost
total number of buildings for each type
total cost for each type

**Comment by ywkim312** [comment]
This issue is moved to https://github.com/navarroc/pyincore-datawolf/issues/4[https://github.com/navarroc/pyincore-datawolf/issues/4](url)
